# Generated by Django 5.0.1 on 2024-08-27 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scannedurls',
            old_name='_id',
            new_name='url_id',
        ),
    ]
