# Generated by Django 5.0.1 on 2024-08-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename__id_scannedurls_url_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedurls',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
