# Generated by Django 5.0.1 on 2024-08-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_scannedurls_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedurls',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scannedurls',
            name='scan_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scannedurls',
            name='url_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
